services:
  db:
    container_name: workout_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
